<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="format" nsURI="http://srg.aut.uah.es/tmtcif/format" nsPrefix="tmtcif">
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatFormatType">
    <eLiterals name="TM" literal="TM"/>
    <eLiterals name="TC" value="1" literal="TC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatFormat" eSuperTypes="common.ecore#//TMTCIFModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TMTCIFFormatFormatType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CSField" upperBound="-1"
        eType="#//TMTCIFFormatCSField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CSFormulaField" upperBound="-1"
        eType="#//TMTCIFFormatCSFormulaField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VSField" upperBound="-1"
        eType="#//TMTCIFFormatVSField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FDICField" upperBound="-1"
        eType="#//TMTCIFFormatFDICField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VRFieldSize" upperBound="-1"
        eType="#//TMTCIFFormatVRFieldSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AField" upperBound="-1"
        eType="#//TMTCIFFormatAField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AIField" upperBound="-1"
        eType="#//TMTCIFFormatAIField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatFieldType">
    <eLiterals name="structured" literal="structured"/>
    <eLiterals name="uint" value="1" literal="uint"/>
    <eLiterals name="flag" value="2" literal="flag"/>
    <eLiterals name="enumerated" value="3" literal="enumerated"/>
    <eLiterals name="bit_vector" value="4" literal="bit_vector"/>
    <eLiterals name="byte_vector" value="5" literal="byte_vector"/>
    <eLiterals name="float" value="6" literal="float"/>
    <eLiterals name="deduced" value="7" literal="deduced"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatFieldByteOrder">
    <eLiterals name="big_endian" literal="big_endian"/>
    <eLiterals name="little_endian" value="1" literal="little_endian"/>
    <eLiterals name="na" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatSFieldFirstBit">
    <eLiterals name="MSB" literal="MSB"/>
    <eLiterals name="LSB" value="1" literal="LSB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatCheckType">
    <eLiterals name="crc16"/>
    <eLiterals name="checksum16" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatField" abstract="true" eSuperTypes="common.ecore#//TMTCIFModelObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pfid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatCSField" eSuperTypes="#//TMTCIFFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TMTCIFFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//TMTCIFFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//TMTCIFFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//TMTCIFFormatBytesBits"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//TMTCIFFormatBytesBits" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatCSFormulaField" eSuperTypes="#//TMTCIFFormatCSField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" lowerBound="1"
        eType="#//TMTCIFFormatFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatVSField" eSuperTypes="#//TMTCIFFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TMTCIFFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//TMTCIFFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//TMTCIFFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constSize" lowerBound="1"
        eType="#//TMTCIFFormatBytesBits" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableSize" lowerBound="1"
        eType="#//TMTCIFFormatVariableSize" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxSize" lowerBound="1"
        eType="#//TMTCIFFormatBytesBits" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//TMTCIFFormatBytesBits" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatVRFieldSize" eSuperTypes="#//TMTCIFFormatField"/>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatFDICField" eSuperTypes="#//TMTCIFFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkType" lowerBound="1"
        eType="#//TMTCIFFormatCheckType" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//TMTCIFFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//TMTCIFFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//TMTCIFFormatBytesBits"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floatingOffset" lowerBound="1"
        eType="#//TMTCIFFormatFloatingOffset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortedFieldsToCheck" lowerBound="1"
        eType="#//TMTCIFFormatSortedFieldsToCheck" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatAField" eSuperTypes="#//TMTCIFFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TMTCIFFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//TMTCIFFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//TMTCIFFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayDimension" lowerBound="1"
        eType="#//TMTCIFFormatArrayDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//TMTCIFFormatBytesBits"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalOffset" lowerBound="1"
        eType="#//TMTCIFFormatBytesBits" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatAIField" eSuperTypes="#//TMTCIFFormatField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TMTCIFFormatFieldType"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byteOrder" lowerBound="1"
        eType="#//TMTCIFFormatFieldByteOrder" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstBit" lowerBound="1"
        eType="#//TMTCIFFormatSFieldFirstBit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayRef" lowerBound="1"
        eType="#//TMTCIFFormatArrayRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//TMTCIFFormatBytesBits"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localOffset" lowerBound="1"
        eType="#//TMTCIFFormatBytesBits" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatBytesBits">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bits" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slope" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intercept" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatUnit">
    <eLiterals name="bytes"/>
    <eLiterals name="bits" value="1"/>
    <eLiterals name="halfword" value="2"/>
    <eLiterals name="string10" value="3"/>
    <eLiterals name="string17" value="4"/>
    <eLiterals name="string69" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TMTCIFFormatPower">
    <eLiterals name="_2" literal="2"/>
    <eLiterals name="_2_with_0" value="1" literal="2_with_0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatVariableSize">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//TMTCIFFormatUnit"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" eType="#//TMTCIFFormatPower"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatFloatingOffset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatSortedFieldsToCheck">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldToCheck" upperBound="-1"
        eType="#//TMTCIFFormatFieldToCheck" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatFieldToCheck">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatArrayDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxItems" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TMTCIFFormatArrayRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fidRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
